
-- 1. CRIAÇÃO DA TABELA DE LEADS
create table if not exists public.leads (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    
    -- Dados Pessoais
    name text,
    email text,
    phone text,
    
    -- Controle de Estado e Eventos
    status text default 'started_checkout', -- started_checkout, initiated_purchase, purchased
    last_event_id text, -- ID gerado no front (Lead-timestamp...) para desduplicação
    
    -- Dados do Produto/Oferta
    offer_name text,
    product_id text,
    offer_value numeric,
    selected_ticket text, -- vip, vip_duplo, diamond
    total_value numeric,
    
    -- Tracking Facebook
    fbp text,
    fbc text,
    user_agent text,
    page_url text,
    
    -- UTMs
    utm_source text,
    utm_medium text,
    utm_campaign text,
    utm_term text,
    utm_content text,
    
    -- Campos Adicionais (Hotmart, etc)
    hotmart_transaction text
);

-- Habilitar RLS (Row Level Security) - Opcional, mas recomendado
alter table public.leads enable row level security;

-- Política para permitir INSERT anônimo (Frontend)
create policy "Allow anonymous inserts"
on public.leads for insert
to anon
with check (true);

-- Política para permitir UPDATE anônimo (Frontend - Passo 2)
-- Nota: Em produção rigorosa, usaríamos autenticação ou procedure, mas para landing page isso funciona
create policy "Allow anonymous updates based on email"
on public.leads for update
to anon
using (true);

-- 2. CRIAÇÃO DO GATILHO (WEBHOOK) PARA A EDGE FUNCTION
-- Certifique-se de ter deployado a função 'meta-capi' antes.

-- Trigger que dispara a cada INSERT ou UPDATE na tabela leads
create trigger "trigger_meta_capi"
after insert or update on public.leads
for each row
execute function supabase_functions.http_request(
  'https://qbwzqiawxtzmnexurzey.supabase.co/functions/v1/meta-capi', -- URL da sua Edge Function
  'POST',
  '{"Content-type":"application/json"}',
  '{}',
  '1000'
);
